import { active, partyBalance, transactions, priceHistory, outstanding, today, cents } from '../domain.js';
import { e, currency, dateLabel, field, button, options, badge, empty } from '../ui.js';
import { paymentModes } from './invoice.js';
export function masterForm(state, kind, id = '') {
  const row = state[kind].find(row => row.id === id) || {};
  const parties = kind === 'parties';
  return `<form id="master-form" data-kind="${kind}" data-id="${e(id)}" data-version="${e(row.updatedAt || '')}"><div class="form-grid">${field('Name', 'name', row.name, 'required autofocus class="master-name"')}${parties ? `<label class="field"><span>Party type</span><select name="type">${options(['customer', 'supplier', 'both'], row.type || 'both')}</select></label>${field('Phone', 'phone', row.phone, 'type="tel"')}${field('GSTIN', 'gstin', row.gstin)}${field('Opening balance', 'openingBal', row.openingBal || 0, 'type="number" step="0.01" inputmode="decimal"')}<p class="muted tiny">Positive = collect from party; negative = pay party.</p>${field('Address', 'address', row.address)}<p class="muted tiny">Opening-balance payments are tracked separately in the party ledger.</p>` : `${field('Unit', 'unit', row.unit || 'Pcs')}${field('Sale rate', 'saleRate', row.saleRate || 0, 'type="number" min="0" step="0.01" inputmode="decimal"')}${field('Purchase rate', 'purchaseRate', row.purchaseRate || 0, 'type="number" min="0" step="0.01" inputmode="decimal"')}${field('GST (%)', 'gst', row.gst || 0, 'type="number" min="0" max="100" step="0.01"')}${field('HSN', 'hsn', row.hsn)}${field('Brand / colour', 'colour', row.colour || row.brand)}${field('SKU', 'sku', row.sku)}`}</div><p class="form-error" role="alert"></p><div class="dialog-actions">${button('Cancel', 'close-dialog', '', 'subtle')}<button type="submit" class="button primary">Save ${parties ? 'party' : 'item'}</button></div></form>`;
}
export function documentDetail(state, kind, id) {
  const doc = state[kind].find(row => row.id === id);
  if (!doc) throw new Error('Bill not found.');
  const sale = kind === 'invoices';
  const saved = (doc.payments || []).filter(p => !p.voidedAt);
  return `<div class="detail-heading"><div><h3>${e(doc.partyName || 'Cash')}</h3><p>${dateLabel(doc.date)}${doc.due ? ` · Due ${dateLabel(doc.due)}` : ''}</p></div>${badge(doc)}</div><div class="detail-metrics"><div><span>Total</span><strong>${currency(doc.total)}</strong></div><div><span>Paid / adjusted</span><strong>${currency(doc.paid)}</strong></div><div><span>Balance</span><strong>${currency(active(doc) ? doc.balance : 0)}</strong></div></div><div class="actions wrap">${button('Print', 'print-document', `data-kind="${kind}" data-id="${e(id)}"`, 'secondary')}${active(doc) ? button('Edit bill', 'edit-document', `data-kind="${kind}" data-id="${e(id)}"`, 'subtle') + (doc.balance > 0 && doc.dispatchStatus !== 'draft' ? button(sale ? 'Collect payment' : 'Payment out', 'open-payment', `data-kind="${kind}" data-id="${e(id)}"`, 'primary') : '') + (sale && doc.dispatchStatus !== 'draft' ? button(doc.dispatchStatus === 'dispatched' ? 'Mark pending' : 'Mark dispatched', 'document-status', `data-kind="${kind}" data-id="${e(id)}" data-status="${doc.dispatchStatus === 'dispatched' ? 'pending' : 'dispatched'}"`, 'subtle') : '') + button('Cancel bill', 'document-status', `data-kind="${kind}" data-id="${e(id)}" data-status="cancelled"`, 'subtle danger') : button('Restore bill', 'document-status', `data-kind="${kind}" data-id="${e(id)}" data-status="restored"`, 'primary')}</div>
    ${(doc.items || []).length ? `<div class="table-wrap"><table><thead><tr><th>Item</th><th>Qty</th><th>Rate</th><th class="number">Amount</th></tr></thead><tbody>${doc.items.map(item => `<tr><td>${e(item.name)}<small>${e([item.colour, item.packType, item.packCount ? `${item.packCount} packs` : ''].filter(Boolean).join(' · '))}</small></td><td>${e(item.qty)} ${e(item.unit)}</td><td>${currency(item.rate)}</td><td class="number">${currency(item.amt)}</td></tr>`).join('')}</tbody></table></div>` : '<p class="info-strip">Amount-only bill</p>'}<div class="detail-summary"><span>Subtotal ${currency(doc.subtotal ?? doc.total)}</span><span>Discount ${currency(doc.discount)}</span><span>Tax ${currency(doc.taxAmt)}</span></div>${doc.notes ? `<p class="notes">${e(doc.notes)}</p>` : ''}${doc.photoData && /^data:image\/(png|jpeg|webp);base64,/.test(doc.photoData) ? `<details><summary>View supplier bill photo</summary><img class="bill-photo" src="${e(doc.photoData)}" alt="Supplier bill attachment"></details>` : ''}<h3 class="subheading">Payment history</h3>${saved.length ? `<div class="payment-history">${saved.map(payment => `<div><span><strong>${dateLabel(payment.date)}</strong><small>${e(payment.mode)} · ${e(payment.note)}</small></span><strong>${currency(payment.amt)}</strong>${active(doc) ? button('Reverse', 'void-payment', `data-kind="${kind}" data-id="${e(id)}" data-payment="${e(payment.id)}"`, 'subtle danger') : ''}</div>`).join('')}</div>` : '<p class="muted">No payments recorded.</p>'}`;
}
export function partyLedger(state, id) {
  const party = state.parties.find(row => row.id === id);
  if (!party) throw new Error('Party not found.');
  const balance = partyBalance(state, party);
  const rows = transactions(state).filter(row => row.partyId === id);
  const openingPaid = state.openingPayments.filter(p => p.partyId === id && !p.voidedAt).reduce((sum, p) => sum + cents(p.amt), 0);
  const openingDue = Math.max(0, Math.abs(cents(party.openingBal)) - openingPaid) / 100;
  return `<div class="detail-heading"><div><h3>${e(party.name)}</h3><p>${e(party.phone || '')} ${e(party.gstin || '')}</p></div><div class="ledger-balance"><small>${balance >= 0 ? 'Net amount to collect' : 'Net amount to pay'}</small><strong>${currency(Math.abs(balance))}</strong></div></div><div class="actions wrap">${button('New sale', 'new-for-party', `data-kind="invoices" data-id="${e(id)}"`, 'primary')}${button('New purchase', 'new-for-party', `data-kind="purchases" data-id="${e(id)}"`, 'secondary')}${button('Payment in', 'open-payment', `data-direction="in" data-party="${e(id)}"`, 'subtle')}${button('Payment out', 'open-payment', `data-direction="out" data-party="${e(id)}"`, 'subtle')}${openingDue > 0 ? button('Settle opening balance', 'opening-payment', `data-id="${e(id)}"`, 'subtle') : ''}</div><p class="info-strip">Opening balance: ${currency(party.openingBal)} · Opening amount still due: ${currency(openingDue)}. Sales add to the balance; purchases reduce it.</p>${rows.length ? `<div class="table-wrap"><table class="responsive-table"><thead><tr><th>Date / type</th><th>Reference</th><th class="number">Amount</th><th>Mode</th></tr></thead><tbody>${rows.map(row => `<tr><td data-label="Date">${dateLabel(row.date)}<small>${e(row.type)}${row.cancelled ? ' · cancelled' : ''}</small></td><td data-label="Reference">${row.collection ? `<button class="text-button" data-action="view-document" data-kind="${row.collection}" data-id="${e(row.documentId || row.id)}">${e(row.reference)}</button>` : e(row.reference)}</td><td class="number" data-label="Amount">${currency(row.amount)}</td><td data-label="Mode">${e(row.mode || '—')}${!row.collection && row.amt != null ? button('Reverse', 'void-payment', `data-kind="openingPayments" data-payment="${e(row.id)}" data-id="${e(id)}"`, 'subtle') : ''}</td></tr>`).join('')}</tbody></table></div>` : empty('No transactions for this party')}`;
}
export function renderPriceHistory(state, editor, lineId) {
  const line = editor.draft.items.find(row => row.id === lineId);
  if (!line) throw new Error('Item not found.');
  const rates = priceHistory(state, line, editor.draft.partyId, 5, editor.kind);
  return `<p class="info-strip">${editor.draft.partyId ? 'Prices for the selected party' : 'Prices across all parties'} · ${e(line.unit || 'Pcs')} · Recorded unit rates, before bill-level discounts / tax.</p>${rates.length ? `<div class="price-options">${rates.map(rate => `<div><span><strong>${currency(rate.rate)} / ${e(rate.unit)}</strong><small>${e(rate.partyName)} · ${dateLabel(rate.date)} · ${e(rate.invoiceNo)}</small></span>${button('Use price', 'use-price', `data-line="${e(lineId)}" data-rate="${rate.rate}"`, 'secondary')}</div>`).join('')}</div>` : empty('No earlier price', 'No matching item, unit, brand and party found in active bills.')}`;
}
export function paymentForm(state, direction = 'in', partyId = '', documentId = '') {
  const collection = direction === 'out' ? 'purchases' : 'invoices';
  const doc = state[collection].find(row => row.id === documentId);
  if (doc) partyId = doc.partyId || '';
  return `<form id="payment-form" data-direction="${direction}" data-document="${e(documentId)}"><div class="form-grid"><label class="field span-2"><span>Party</span><select name="partyId" id="payment-party"><option value="">Cash / unassigned bills</option>${state.parties.filter(p => !p.deletedAt).map(p => `<option value="${e(p.id)}" ${p.id === partyId ? 'selected' : ''}>${e(p.name)}</option>`).join('')}</select></label>${field('Date', 'date', today(), 'type="date" required')}${field(direction === 'out' ? 'Amount paid' : 'Amount received', 'amount', doc?.balance || '', 'id="payment-amount" type="number" min="0" step="0.01" inputmode="decimal"')}<label class="field"><span>Mode</span><select name="mode">${options(paymentModes, 'Cash')}</select></label>${field('Settlement discount', 'discount', 0, 'type="number" min="0" step="0.01" inputmode="decimal"')}${field('Note', 'note', '', 'placeholder="Payment reference"')}</div><div class="section-title"><h3>Allocate to bills</h3>${button('Allocate oldest first', 'auto-allocate', '', 'subtle')}</div><div id="allocation-bills"></div><p id="allocation-summary" class="info-strip"></p><p class="form-error" role="alert"></p><div class="dialog-actions">${button('Cancel', 'close-dialog', '', 'subtle')}<button type="submit" class="button primary">Save payment ${direction}</button></div></form>`;
}
export function allocationMarkup(state, direction, partyId, documentId = '') {
  const rows = outstanding(state, direction).filter(row => (row.partyId || '') === partyId && (!documentId || row.id === documentId));
  return rows.length ? rows.map(row => `<label class="allocation-row"><span><strong>${e(row.invoiceNo || row.billNo)}</strong><small>${dateLabel(row.date)} · Due ${currency(row.balance)}</small></span><input aria-label="Allocate to ${e(row.invoiceNo || row.billNo)}" name="allocate:${e(row.id)}" type="number" min="0" max="${row.balance}" step="0.01" inputmode="decimal" value="${documentId ? row.balance : ''}" placeholder="0.00"></label>`).join('') : empty('No pending bills', 'Choose another party or settle its opening balance from the ledger.');
}
export function openingPaymentForm(state, partyId) {
  const party = state.parties.find(row => row.id === partyId);
  return `<form id="opening-form" data-party="${e(partyId)}" data-direction="${Number(party.openingBal) < 0 ? 'out' : 'in'}"><p class="info-strip">This payment is applied to ${e(party.name)}’s opening balance.</p><div class="form-grid">${field('Date', 'date', today(), 'type="date" required')}${field('Amount', 'amount', '', 'type="number" min="0.01" step="0.01" required')}<label class="field"><span>Mode</span><select name="mode">${options(paymentModes, 'Cash')}</select></label>${field('Note', 'note')}</div><p class="form-error" role="alert"></p><div class="dialog-actions"><button type="submit" class="button primary">Save opening payment</button></div></form>`;
}
