import { active, partyBalance, outstanding, transactions, today } from '../domain.js';
import { e, currency, dateLabel, button, empty, badge, pageHead, field, options } from '../ui.js';
function match(row, filter) {
  return (!filter.search || [row.name, row.partyName, row.invoiceNo, row.billNo, row.notes, row.reference].join(' ').toLowerCase().includes(filter.search.toLowerCase())) && (!filter.from || !row.date || row.date >= filter.from) && (!filter.to || !row.date || row.date <= filter.to);
}
function filterBar(filter, statuses = null) {
  return `<div class="filter-bar">${field('Search', 'search', filter.search || '', 'id="list-search" placeholder="Search party or bill…" data-filter="search" type="search"')}${field('From', 'from', filter.from || '', 'data-filter="from" type="date"')}${field('To', 'to', filter.to || '', 'data-filter="to" type="date"')}${statuses ? `<label class="field"><span>Status</span><select data-filter="status">${options(statuses, filter.status || 'All')}</select></label>` : ''}${button('Clear', 'clear-filter', '', 'subtle')}</div>`;
}
function pager(rows, filter) {
  const pages = Math.max(1, Math.ceil(rows.length / 25));
  filter.page = Math.min(filter.page || 1, pages);
  const start = (filter.page - 1) * 25;
  return { rows: rows.slice(start, start + 25), html: `<div class="pagination"><span>${rows.length ? start + 1 : 0}–${Math.min(start + 25, rows.length)} of ${rows.length}</span><div class="actions">${button('Previous', 'page-list', `data-step="-1" ${filter.page <= 1 ? 'disabled' : ''}`, 'subtle')}<span>Page ${filter.page} / ${pages}</span>${button('Next', 'page-list', `data-step="1" ${filter.page >= pages ? 'disabled' : ''}`, 'subtle')}</div></div>` };
}
export function documentTable(rows, collection, { compact = false } = {}) {
  if (!rows.length) return empty('No bills yet', 'Create a bill or adjust your filters.');
  return `<div class="table-wrap"><table class="responsive-table"><thead><tr><th>Bill / date</th><th>Party</th><th class="number">Amount</th><th class="number">Balance</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.map(doc => `<tr><td data-label="Bill"><button class="text-button" data-action="view-document" data-kind="${collection}" data-id="${e(doc.id)}">${e(doc.invoiceNo || doc.billNo || 'Purchase')}</button><small>${dateLabel(doc.date)}</small></td><td data-label="Party"><strong>${e(doc.partyName || 'Cash')}</strong>${doc.due ? `<small>Due ${dateLabel(doc.due)}</small>` : ''}</td><td class="number" data-label="Amount">${currency(doc.total)}</td><td class="number ${Number(doc.balance) > 0 ? 'warning-text' : ''}" data-label="Balance">${currency(active(doc) ? doc.balance : 0)}</td><td data-label="Status">${badge(doc)}${collection === 'invoices' && doc.dispatchStatus === 'dispatched' ? '<small>Dispatched</small>' : ''}</td><td data-label="Actions"><div class="row-actions">${button('View', 'view-document', `data-kind="${collection}" data-id="${e(doc.id)}"`, 'subtle')}${!compact && active(doc) ? button('Edit', 'edit-document', `data-kind="${collection}" data-id="${e(doc.id)}"`, 'subtle') : ''}${active(doc) && doc.dispatchStatus !== 'draft' && doc.balance > 0 ? button(collection === 'invoices' ? 'Collect' : 'Pay', 'open-payment', `data-kind="${collection}" data-id="${e(doc.id)}"`, 'secondary') : ''}</div></td></tr>`).join('')}</tbody></table></div>`;
}
export function renderDashboard(state) {
  const invoices = state.invoices.filter(d => active(d) && d.dispatchStatus !== 'draft');
  const purchases = state.purchases.filter(active);
  const retail = state.retail.filter(active);
  const saleTotal = invoices.reduce((sum, d) => sum + Number(d.total), 0) + retail.reduce((sum, d) => sum + Number(d.amount), 0);
  const receive = outstanding(state, 'in').reduce((sum, d) => sum + Number(d.balance), 0);
  const pay = outstanding(state, 'out').reduce((sum, d) => sum + Number(d.balance), 0);
  const pending = invoices.filter(d => d.dispatchStatus !== 'dispatched').length;
  const cards = [['Total sales', saleTotal, `${invoices.length} invoices + ${retail.length} retail entries`, ''], ['To collect', receive, 'Pending invoice balances', 'orange'], ['To pay', pay, `${purchases.length} purchase bills`, 'blue'], ['Pending dispatch', pending, 'Invoices waiting to go out', 'plain']];
  const recent = [...state.invoices].filter(d => !d.deletedAt).sort((a, b) => (b.createdAt || b.date).localeCompare(a.createdAt || a.date)).slice(0, 6);
  return `${pageHead('Business overview', 'Your sales, purchases and dues, together.', button('New sale', 'navigate', 'data-page="new-sale"', 'primary') + button('New purchase', 'navigate', 'data-page="new-purchase"', 'secondary'))}<div class="stat-grid">${cards.map(([title, value, hint, style]) => `<section class="stat-card ${style}"><span>${title}</span><strong>${style === 'plain' ? value : currency(value)}</strong><small>${hint}</small></section>`).join('')}</div><section class="quick-grid">${[['Payment in', 'payment-in', 'Receive money from customers'], ['Payment out', 'payment-out', 'Pay suppliers and allocate bills'], ['Add party', 'parties', 'Customer and supplier ledgers'], ['Retail entry', 'retail', 'Record counter sales quickly']].map(([title, page, text]) => `<button class="quick-card" data-action="navigate" data-page="${page}"><strong>${title}</strong><span>${text}</span><span class="arrow">→</span></button>`).join('')}</section><section class="card"><div class="section-title"><div><h2>Recent sale invoices</h2><p class="muted">Your latest entries at a glance</p></div>${button('View all sales', 'navigate', 'data-page="sales"', 'subtle')}</div>${documentTable(recent, 'invoices', { compact: true })}</section><div class="info-strip">Invoice balances above exclude opening balances. Open a party ledger to see its complete balance.</div>`;
}
export function renderDocuments(state, collection, filter) {
  const sale = collection === 'invoices';
  const rows = state[collection].filter(d => !d.deletedAt && match(d, filter)).filter(d => !filter.status || filter.status === 'All' || (filter.status === 'Cancelled' ? !active(d) : filter.status === 'Draft' ? d.dispatchStatus === 'draft' : filter.status === 'Paid' ? active(d) && d.dispatchStatus !== 'draft' && d.balance <= 0 : filter.status === 'Unpaid' ? active(d) && d.dispatchStatus !== 'draft' && d.balance > 0 : filter.status === 'Pending dispatch' ? active(d) && d.dispatchStatus === 'pending' : d.dispatchStatus === 'dispatched')).sort((a, b) => b.date.localeCompare(a.date) || (b.createdAt || '').localeCompare(a.createdAt || ''));
  const page = pager(rows, filter);
  const total = rows.filter(d => active(d) && d.dispatchStatus !== 'draft').reduce((sum, d) => sum + Number(d.total), 0);
  return `${pageHead(sale ? 'Sale invoices' : 'Purchase bills', 'Search, edit, print and settle your bills.', button('Export CSV', 'export-csv', `data-type="${collection}"`, 'subtle') + button('Bulk / previous bills', 'navigate', `data-page="${sale ? 'bulk-sales' : 'bulk-purchases'}"`, 'secondary') + button(sale ? 'New sale' : 'New purchase', 'navigate', `data-page="${sale ? 'new-sale' : 'new-purchase'}"`, 'primary'))}<section class="card">${filterBar(filter, sale ? ['All', 'Unpaid', 'Paid', 'Draft', 'Pending dispatch', 'Dispatched', 'Cancelled'] : ['All', 'Unpaid', 'Paid', 'Cancelled'])}<div class="list-summary"><span>${rows.length} matching bills</span><strong>Total ${currency(total)}</strong></div>${documentTable(page.rows, collection)}${page.html}</section>`;
}
export function renderMasters(state, collection, filter) {
  const parties = collection === 'parties';
  const archived = filter.status === 'Archived';
  const rows = state[collection].filter(row => Boolean(row.deletedAt) === archived && match(row, filter)).sort((a, b) => a.name.localeCompare(b.name));
  const page = pager(rows, filter);
  return `${pageHead(parties ? 'Parties' : 'Items', parties ? 'Customers, suppliers and their complete transaction history.' : 'Your product catalogue, rates and packing units.', button('Export CSV', 'export-csv', `data-type="${collection}"`, 'subtle') + button(parties ? 'Add party' : 'Add item', 'edit-master', `data-kind="${collection}"`, 'primary'))}<section class="card"><div class="filter-bar">${field('Search', 'search', filter.search || '', 'id="list-search" data-filter="search" type="search" placeholder="Search by name…"')}<label class="field"><span>Records</span><select data-filter="status">${options(['Active', 'Archived'], filter.status || 'Active')}</select></label></div>${rows.length ? `<div class="table-wrap"><table class="responsive-table"><thead><tr><th>Name</th>${parties ? '<th>Contact</th><th>Type</th><th class="number">Net balance</th>' : '<th>Unit / HSN</th><th class="number">Sale price</th><th class="number">Purchase price</th>'}<th>Actions</th></tr></thead><tbody>${page.rows.map(row => `<tr><td data-label="Name"><strong>${e(row.name)}</strong><small>${e(parties ? row.gstin : row.colour || row.brand || row.sku)}</small></td>${parties ? `<td data-label="Contact">${e(row.phone || '—')}<small>${e(row.address)}</small></td><td data-label="Type">${e(row.type || 'both')}</td><td class="number" data-label="Balance">${currency(Math.abs(partyBalance(state, row)))}<small>${partyBalance(state, row) >= 0 ? 'To collect' : 'To pay'}</small></td>` : `<td data-label="Unit">${e(row.unit || 'Pcs')}<small>${e(row.hsn)}</small></td><td class="number" data-label="Sale price">${currency(row.saleRate)}</td><td class="number" data-label="Purchase price">${currency(row.purchaseRate)}</td>`}<td data-label="Actions"><div class="row-actions">${archived ? button('Restore', 'restore-master', `data-kind="${collection}" data-id="${e(row.id)}"`, 'secondary') : (parties ? button('Ledger', 'party-ledger', `data-id="${e(row.id)}"`, 'secondary') : '') + button('Edit', 'edit-master', `data-kind="${collection}" data-id="${e(row.id)}"`, 'subtle') + button('Archive', 'archive-master', `data-kind="${collection}" data-id="${e(row.id)}"`, 'subtle danger')}</div></td></tr>`).join('')}</tbody></table></div>` : empty(archived ? 'No archived records' : parties ? 'Add your first party' : 'Add your first item', 'Use the add button above or import a CSV from Data & Sync.')}${page.html}</section>`;
}
export function renderTransactions(state, filter, mode = 'all') {
  const rows = transactions(state).filter(row => match(row, filter) && (mode === 'all' || mode === 'in' && row.type === 'Payment in' || mode === 'out' && row.type === 'Payment out'));
  const page = pager(rows, filter);
  return `${pageHead(mode === 'all' ? 'Transactions' : mode === 'in' ? 'Payment in' : 'Payment out', 'Track money movement and the bills behind it.', button('Export CSV', 'export-csv', 'data-type="transactions"', 'subtle') + (mode !== 'all' ? button('Record payment', 'open-payment', `data-direction="${mode}"`, 'primary') : ''))}<section class="card">${filterBar(filter)}${page.rows.length ? `<div class="table-wrap"><table class="responsive-table"><thead><tr><th>Date / type</th><th>Party</th><th>Reference</th><th class="number">Amount</th><th>Mode / note</th></tr></thead><tbody>${page.rows.map(row => `<tr><td data-label="Date">${dateLabel(row.date)}<small>${e(row.type)}${row.cancelled ? ' · cancelled bill' : ''}</small></td><td data-label="Party">${e(row.partyName)}</td><td data-label="Reference">${row.collection ? `<button class="text-button" data-action="view-document" data-kind="${row.collection}" data-id="${e(row.documentId || row.id)}">${e(row.reference)}</button>` : e(row.reference)}</td><td class="number" data-label="Amount">${currency(row.amount)}</td><td data-label="Mode">${e(row.mode || '—')}<small>${e(row.note)}</small></td></tr>`).join('')}</tbody></table></div>` : empty('No matching transactions', 'Record your first sale, purchase or payment.')}${page.html}</section>`;
}
export function renderRetail(state, filter) {
  const archived = filter.status === 'Archived';
  const rows = state.retail.filter(row => Boolean(row.deletedAt) === archived && match(row, filter)).sort((a, b) => b.date.localeCompare(a.date));
  const page = pager(rows, filter);
  return `${pageHead('Retail sales', 'A quick daily entry for counter sales.')}<form id="retail-form" class="card"><div class="form-grid">${field('Date', 'date', today(), 'type="date" required')}${field('Amount', 'amount', '', 'type="number" min="0.01" step="0.01" inputmode="decimal" required')}${field('Notes', 'notes', '', 'placeholder="Cash / UPI / daily total"')}<div class="field"><span>&nbsp;</span><button type="submit" class="button primary">Save retail sale</button></div></div></form><section class="card">${filterBar(filter, ['All', 'Archived'])}<div class="list-summary"><span>${rows.length} entries</span><strong>${currency(rows.reduce((sum, row) => sum + Number(row.amount), 0))}</strong></div>${rows.length ? `<div class="table-wrap"><table class="responsive-table"><thead><tr><th>Date</th><th>Notes</th><th class="number">Amount</th><th>Action</th></tr></thead><tbody>${page.rows.map(row => `<tr><td data-label="Date">${dateLabel(row.date)}</td><td data-label="Notes">${e(row.notes)}</td><td class="number" data-label="Amount">${currency(row.amount)}</td><td data-label="Action">${button(archived ? 'Restore' : 'Archive', archived ? 'restore-master' : 'archive-master', `data-kind="retail" data-id="${e(row.id)}"`, 'subtle')}</td></tr>`).join('')}</tbody></table></div>` : empty('No retail entries')}${page.html}</section>`;
}
export function renderReports(state, filter) {
  const sales = state.invoices.filter(d => active(d) && d.dispatchStatus !== 'draft' && match(d, filter));
  const purchases = state.purchases.filter(d => active(d) && match(d, filter));
  const retail = state.retail.filter(d => active(d) && match(d, filter));
  const itemMap = new Map();
  for (const doc of sales) for (const item of doc.items || []) {
    const id = `${item.itemId || item.name}|${item.unit || 'Pcs'}|${item.colour || ''}`;
    const row = itemMap.get(id) || { name: item.name, unit: item.unit || 'Pcs', qty: 0, amount: 0 };
    row.qty += Number(item.qty || 0); row.amount += Number(item.amt ?? Number(item.qty || 0) * Number(item.rate || 0)); itemMap.set(id, row);
  }
  const itemPage = pager([...itemMap.values()].sort((a, b) => b.amount - a.amount), filter);
  return `${pageHead('Reports', 'Sales, purchases, item movement and pending balances.', button('Export transactions', 'export-csv', 'data-type="transactions"', 'secondary'))}<section class="card">${filterBar(filter)}<div class="stat-grid"><div class="stat-card"><span>Wholesale sales</span><strong>${currency(sales.reduce((s, d) => s + Number(d.total), 0))}</strong><small>${sales.length} invoices</small></div><div class="stat-card blue"><span>Purchases</span><strong>${currency(purchases.reduce((s, d) => s + Number(d.total), 0))}</strong><small>${purchases.length} bills</small></div><div class="stat-card orange"><span>Retail sales</span><strong>${currency(retail.reduce((s, d) => s + Number(d.amount), 0))}</strong><small>${retail.length} entries</small></div><div class="stat-card"><span>Sales including retail</span><strong>${currency(sales.reduce((s, d) => s + Number(d.total), 0) + retail.reduce((s, d) => s + Number(d.amount), 0))}</strong><small>For the selected period</small></div></div></section><section class="card"><div class="section-title"><h2>Item-wise sales</h2></div>${itemMap.size ? `<div class="table-wrap"><table class="responsive-table"><thead><tr><th>Item</th><th class="number">Quantity</th><th class="number">Sales before bill discount / tax</th></tr></thead><tbody>${itemPage.rows.map(row => `<tr><td data-label="Item">${e(row.name)}</td><td class="number" data-label="Quantity">${row.qty.toLocaleString('en-IN')} ${e(row.unit)}</td><td class="number" data-label="Value">${currency(row.amount)}</td></tr>`).join('')}</tbody></table></div>` : empty('No item sales in this period')}${itemPage.html}</section><section class="card"><div class="section-title"><h2>Pending collections</h2></div>${documentTable(outstanding(state, 'in').filter(d => match(d, filter)).slice(0, 25), 'invoices', { compact: true })}</section><section class="card"><div class="section-title"><h2>Pending supplier payments</h2></div>${documentTable(outstanding(state, 'out').filter(d => match(d, filter)).slice(0, 25), 'purchases', { compact: true })}</section>`;
}
export function renderAudit(state, filter) {
  const rows = [...state.audit].filter(row => !filter.search || `${row.label} ${row.type} ${row.user}`.toLowerCase().includes(filter.search.toLowerCase())).reverse();
  const page = pager(rows, filter);
  return `${pageHead('Activity log', 'A retained history of saves, payments and reversals.')}<section class="card">${field('Search activity', 'search', filter.search || '', 'id="list-search" data-filter="search" type="search"')}${rows.length ? `<ol class="activity-list">${page.rows.map(row => `<li><span class="activity-dot"></span><div><strong>${e(row.label || row.type)}</strong><small>${e(row.user || 'Owner')} · ${e(row.ts ? new Date(row.ts).toLocaleString('en-IN') : '')}</small>${row.details ? `<p>${e(row.details)}</p>` : ''}</div></li>`).join('')}</ol>` : empty('No activity yet')}${page.html}</section>`;
}
