import { e, field, options, button, pageHead } from '../ui.js';
export function renderSettings(state) {
  const settings = state.settings;
  return `${pageHead('Business settings', 'Business details, invoice defaults and print preferences.')}<form id="settings-form" data-version="${e(settings.updatedAt || '')}" data-counter="${e(settings.invNo)}"><section class="card"><div class="section-title"><h2>Business profile</h2></div><div class="form-grid">${field('Business name', 'shopName', settings.shopName, 'required')}${field('Owner', 'owner', settings.owner)}${field('Phone', 'phone', settings.phone, 'type="tel"')}${field('GSTIN', 'gstin', settings.gstin)}${field('State', 'state', settings.state)}${field('Financial year', 'fy', settings.fy)}<label class="field span-2"><span>Business address</span><textarea name="address" rows="2">${e(settings.address)}</textarea></label></div></section><section class="card"><div class="section-title"><h2>Invoice defaults</h2></div><div class="form-grid">${field('Invoice prefix', 'prefix', settings.prefix)}${field('Next invoice number', 'invNo', settings.invNo, 'type="number" min="1" step="1" required')}<label class="field span-2"><span>Bank / UPI details</span><textarea name="bank" rows="2">${e(settings.bank)}</textarea></label><label class="field span-2"><span>Terms and conditions</span><textarea name="terms" rows="3">${e(settings.terms)}</textarea></label></div><div class="checkbox-grid">${[['packing', 'Packing fields'], ['dispatch', 'Dispatch tracking'], ['retail', 'Retail entries'], ['gst', 'Bill-level tax field']].map(([name, label]) => `<label class="check"><input type="checkbox" name="module:${name}" ${settings.modules?.[name] !== false ? 'checked' : ''}>${label}</label>`).join('')}</div><p class="muted tiny">This version retains the original bill-level tax model. Item GST defaults are stored in your catalogue.</p></section><section class="card"><div class="section-title"><h2>Print preferences</h2></div><div class="form-grid"><label class="field"><span>Paper width</span><select name="print:paper">${options(['A4', '80mm'], settings.printSettings?.paper || 'A4')}</select></label></div><div class="checkbox-grid">${[['showPacking', 'Packing on invoice'], ['showBrand', 'Brand on invoice'], ['showBank', 'Bank details'], ['showTerms', 'Terms']].map(([name, label]) => `<label class="check"><input type="checkbox" name="print:${name}" ${settings.printSettings?.[name] !== false ? 'checked' : ''}>${label}</label>`).join('')}</div></section><section class="card"><div class="section-title"><h2>Custom invoice fields</h2>${button('Add field', 'add-custom-field', '', 'subtle')}</div><div id="custom-fields">${(settings.customFields || []).map(cf => customFieldRow(cf)).join('')}</div></section><p class="form-error" id="settings-error" role="alert"></p><div class="actions"><button type="submit" class="button primary">Save settings</button></div></form>`;
}
export function customFieldRow(cf) {
  return `<div class="custom-row" data-custom-id="${e(cf.id)}">${field('Label', 'label', cf.label, 'required')}<label class="field"><span>Type</span><select name="type">${options(['text', 'number', 'date'], cf.type)}</select></label>${button('Remove', 'remove-custom-field', '', 'subtle danger')}</div>`;
}
export function renderData(store, cloud) {
  const counts = ['invoices', 'purchases', 'parties', 'items'].map(name => `${store.data[name].length} ${name}`).join(' · ');
  return `${pageHead('Data & sync', 'Back up your business, import data and connect your devices.')}
  <section class="card"><div class="section-title"><div><h2>Your billing data</h2><p class="muted">${e(counts)}</p></div><span class="badge neutral">Revision ${store.envelope.revision}</span></div><p class="info-strip">${store.envelope.ownerId ? 'Cloud workspace. Bills can be posted after signing in to this account.' : 'Device-only mode. These bills stay in this browser until you connect cloud storage.'}</p><div class="actions wrap">${button('Download full backup', 'export-backup', '', 'primary')}<label class="button secondary">Restore JSON backup<input class="visually-hidden" id="backup-file" type="file" accept="application/json,.json"></label>${button('Export all transactions CSV', 'export-csv', 'data-type="transactions"', 'subtle')}</div><p class="muted tiny">Backups include bill photos, payments, opening balances and activity history. Old shop4_* browser data is retained as a migration recovery copy.</p></section>
  <section class="card"><div class="section-title"><h2>Cloud connection</h2><span class="badge neutral">${cloud.connected ? e(cloud.session.user.email || 'Signed in') : 'Not connected'}</span></div><p class="muted">Open this private app with the same ChatGPT account on your PC and phone. Your bills are stored in a dedicated cloud database.</p><p class="info-strip">Cloud saves use revision checks and safe retries. Devices check for changes every 8 seconds and on reconnect. A connection is required to post cloud bills; unfinished drafts stay local.</p>
  ${cloud.connected ? `<div class="actions wrap">${button('Refresh now', 'refresh-cloud', '', 'secondary')}${button('Use cloud data', 'use-cloud', '', 'subtle')}<a class="button subtle" href="/signout-with-chatgpt?return_to=/" target="_top">Sign out</a></div>` : cloud.available ? `<a class="button primary" href="/signin-with-chatgpt?return_to=/" target="_top">Sign in with ChatGPT</a>` : '<p class="muted">Cloud sync is available on the hosted app. This local preview stores data only on this device.</p>'}
  ${store.error ? `<p class="form-error" role="alert">${e(store.error)}</p>` : ''}${store.pending ? `<div class="pending-box"><strong>A save needs attention</strong><p>${e(store.pending.type)} · ${e(store.pending.at)}</p><div class="actions">${button('Retry pending save', 'retry-save', '', 'primary')}${button('Download pending operation', 'export-pending', '', 'subtle')}</div></div>` : ''}</section>
  <section class="card"><div class="section-title"><h2>Google Drive & Sheets</h2></div><p class="muted">Save a full backup to your Drive or refresh spreadsheet reports through the optional Google integration.</p><div class="actions wrap">${button('Back up to Drive', 'google-export', `data-type="backup" ${!cloud.googleConfigured ? 'disabled' : ''}`, 'secondary')}${button('Update Google Sheets', 'google-export', `data-type="sheets" ${!cloud.googleConfigured ? 'disabled' : ''}`, 'subtle')}</div><p class="muted tiny">${cloud.googleConfigured ? 'Your Google connection is configured.' : 'Connect your Google account to enable these exports.'} Google credentials stay on the server. A failed export does not affect saved bills.</p></section>
  <section class="card"><div class="section-title"><h2>Import from Excel CSV</h2></div><p class="muted">Save your Excel sheet as UTF-8 CSV. Use your exported items/parties file as a template. Existing IDs update matching records; blank IDs add new records.</p><form id="csv-form"><div class="form-grid"><label class="field"><span>Data type</span><select name="kind">${options(['items', 'parties'], 'items')}</select></label><label class="field span-2"><span>CSV file (up to 500 rows)</span><input name="file" type="file" accept="text/csv,.csv" required></label></div><p class="form-error" role="alert"></p><button type="submit" class="button secondary">Review CSV import</button></form></section>`;
}
